"""
Patient-friendly summarization using facebook/bart-large-cnn.

Takes a clinical transcription (medical jargon) and returns:
  1. A short summary in plain language a patient can understand
  2. Key points as bullet list

DL concept:
  BART is a seq2seq transformer (encoder-decoder architecture).
  We use the pre-trained bart-large-cnn (trained on CNN/DailyMail news articles)
  for abstractive summarization — no fine-tuning needed for a good baseline.
  The model reads the full report and generates NEW sentences, not just extracts.

Run standalone:
    python src/summarize.py
"""

import sys
from pathlib import Path
from typing import Dict

sys.path.append(str(Path(__file__).parent.parent))
from config import SUM_BASE_MODEL, SUM_MAX_INPUT, SUM_MAX_OUTPUT, SUM_MIN_OUTPUT


# ── Lazy loader ───────────────────────────────────────────────────────────────
_summarizer = None


def _get_summarizer():
    global _summarizer
    if _summarizer is None:
        from transformers import pipeline
        print(f"Loading summarization model: {SUM_BASE_MODEL}")
        _summarizer = pipeline(
            "summarization",
            model=SUM_BASE_MODEL,
            device=_get_device(),
        )
    return _summarizer


def _get_device():
    """Use GPU if available, else CPU."""
    import torch
    return 0 if torch.cuda.is_available() else -1


# ── Plain-language prompt wrapper ─────────────────────────────────────────────
_PROMPT_PREFIX = (
    "Summarize the following medical report in simple language "
    "that a patient with no medical background can easily understand. "
    "Focus on what happened, what was found, and what the plan is. "
    "Avoid medical jargon. Do not provide diagnoses or medical advice.\n\n"
    "REPORT:\n"
)


def summarize(text: str) -> Dict[str, str]:
    """
    Generate a patient-friendly summary of a clinical transcription.

    Returns:
        {
          "summary":    "Plain-language paragraph summary",
          "disclaimer": "Non-diagnostic disclaimer text"
        }
    """
    if not text or len(text.strip()) < 50:
        return {
            "summary":    "Report too short to summarize.",
            "disclaimer": _DISCLAIMER,
        }

    summarizer = _get_summarizer()

    # Prepend the plain-language instruction to guide the model
    prompted_text = _PROMPT_PREFIX + text

    # BART has a 1024 token limit — truncate by character count as proxy
    input_text = prompted_text[:SUM_MAX_INPUT * 4]

    result = summarizer(
        input_text,
        max_length=SUM_MAX_OUTPUT,
        min_length=SUM_MIN_OUTPUT,
        do_sample=False,            # greedy/beam search — deterministic output
        num_beams=4,                # beam search: explore 4 candidates
        early_stopping=True,
    )

    summary = result[0]["summary_text"].strip()

    # Clean up any leftover prompt fragments
    summary = summary.replace("REPORT:", "").strip()

    return {
        "summary":    summary,
        "disclaimer": _DISCLAIMER,
    }


_DISCLAIMER = (
    "⚠️ This summary is generated by AI for informational purposes only. "
    "It is NOT a medical diagnosis and does NOT replace the advice of a "
    "licensed healthcare professional. Always consult your doctor."
)


# ── Evaluation helpers ────────────────────────────────────────────────────────
def evaluate_rouge(generated: str, reference: str) -> Dict[str, float]:
    """
    Compute ROUGE scores between generated summary and a reference.
    Used in notebooks/03_evaluate_summarizer.py.
    """
    from rouge_score import rouge_scorer
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)
    scores = scorer.score(reference, generated)
    return {
        "rouge1": round(scores["rouge1"].fmeasure, 4),
        "rouge2": round(scores["rouge2"].fmeasure, 4),
        "rougeL": round(scores["rougeL"].fmeasure, 4),
    }


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    sample = """
    CHIEF COMPLAINT: Chest pain and shortness of breath.

    HISTORY OF PRESENT ILLNESS: The patient is a 58-year-old male with a
    known history of hypertension and hyperlipidemia who presents with acute
    onset substernal chest pain radiating to the left arm, associated with
    diaphoresis and dyspnea. Symptoms began approximately 2 hours ago.

    PHYSICAL EXAMINATION: Blood pressure 162/94 mmHg, heart rate 92 bpm,
    respiratory rate 20/min. Cardiac examination reveals regular rate and rhythm.
    Lungs clear to auscultation bilaterally.

    ASSESSMENT AND PLAN: Acute coronary syndrome cannot be excluded.
    EKG obtained showing ST segment elevation in leads II, III, aVF.
    Patient started on aspirin 325mg, sublingual nitroglycerin, IV heparin.
    Cardiology consulted for emergent cardiac catheterization.
    """

    result = summarize(sample)
    print("── Patient-Friendly Summary ──────────────────────────────")
    print(result["summary"])
    print("\n" + result["disclaimer"])